[32mINFO    [0m integration.test_trust:test_trust.py:75 Connection attempt failed: (0)
Reason: Handshake status 500 Internal Server Error -+-+- {'audit-id': 'd686d961-dd31-49fb-85c7-f11d9aa92524', 'cache-control': 'no-cache, private', 'content-type': 'application/json', 'warning': '299 - "Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens."', 'date': 'Fri, 26 Jul 2024 01:37:12 GMT', 'content-length': '168'} -+-+- b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"error dialing backend: dial tcp 10.0.0.4:10250: connect: connection refused","code":500}\n'

[32mINFO    [0m integration.test_trust:test_trust.py:77 Retrying (1/20)...
[32mINFO    [0m integration.test_trust:test_trust.py:72 Connection established: <class 'juju.client._definitions.FullStatus'>({'applications': {}, 'branches': {}, 'controller_timestamp': '2024-07-26T01:37:16.050977032Z', 'filesystems': [], 'machines': {}, 'model': <class 'juju.client._definitions.ModelStatusInfo'>({'available_version': '', 'cloud_tag': 'cloud-microk8s', 'meter_status': <class 'juju.client._definitions.MeterStatus'>({'color': '', 'message': '', 'unknown_fields': {}}), 'model_status': <class 'juju.client._definitions.DetailedStatus'>({'data': {}, 'err': None, 'info': '', 'kind': '', 'life': '', 'since': '2024-07-26T01:36:42.502156903Z', 'status': 'available', 'version': '', 'unknown_fields': {}}), 'name': 'test', 'region': 'localhost', 'sla': 'unsupported', 'type_': 'caas', 'version': '3.4.4', 'unknown_fields': {}}), 'offers': {}, 'relations': [], 'remote_applications': {}, 'storage': [], 'volumes': [], 'unknown_fields': {}})